[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
name = "dolfinx_optim"
version = "0.2.0"
authors = [{ name = "Jeremy Bleyer", email = "jeremy.bleyer@enpc.fr" }]
description = "Automated Convex Optimization in FEniCSx"
readme = "README.md"
keywords = ["optimization", "PDF"]
requires-python = ">=3.10"
dependencies = ["mosek", "fenics-dolfinx>=0.10,<0.11"]

[tool.setuptools]
zip-safe = false
include-package-data = true

[tool.setuptools.packages]
find = { namespaces = false }
